package com.mojito.mojitoboot.common.mapper;

import com.mojito.mojitoboot.common.daomodel.GoodsStockDO;

public interface GoodsStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Fri Jan 25 00:11:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Fri Jan 25 00:11:56 CST 2019
     */
    int insert(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Fri Jan 25 00:11:56 CST 2019
     */
    int insertSelective(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Fri Jan 25 00:11:56 CST 2019
     */
    GoodsStockDO selectByPrimaryKey(Integer id);

    GoodsStockDO selectByGoodsId(Integer goodsId);

    int updateStock(Integer goodsId,Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Fri Jan 25 00:11:56 CST 2019
     */
    int updateByPrimaryKeySelective(GoodsStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_stock
     *
     * @mbg.generated Fri Jan 25 00:11:56 CST 2019
     */
    int updateByPrimaryKey(GoodsStockDO record);
}